# ДЗ 1 Индекс

# Intro
### работа с файлами и папками

In [1]:
import os

curr_dir = os.getcwd()
filepath = os.path.join(curr_dir, 'test.txt')

### os.path  
путь до файла

In [2]:
# возвращает полный путь до папки/файла по имени файла / папки
print(os.path.abspath(filepath))


# возвращает имя файла / папки по полному ти до него
print(os.path.basename(filepath))


# проверить существование директории - True / False
print(os.path.exists(curr_dir))

C:\Users\User\Женя\GitHub\Программирование\infosearch\seminars\test.txt
test.txt
True


### os.listdir  
возвращает список файлов в данной директории

In [3]:
os.listdir(curr_dir)

['.ipynb_checkpoints', 'sem1_Index.ipynb']

При обходе файлов не забывайте исключать системные директории, такие как .DS_Store

### os.walk
root - начальная директория  
dirs - список поддиректорий (папок)   
files - список файлов в этих поддиректориях  

In [4]:
for root, dirs, files in os.walk(curr_dir):
    for name in files:
        print(os.path.join(root, name))

C:\Users\User\Женя\GitHub\Программирование\infosearch\seminars\sem1_Index.ipynb
C:\Users\User\Женя\GitHub\Программирование\infosearch\seminars\.ipynb_checkpoints\sem1_Index-checkpoint.ipynb


> __os.walk__ возвращает генератор, это значит, что получить его элементы можно только проитерировавшись по нему  
но его легко можно превратить в list и увидеть все его значения

In [5]:
list(os.walk(curr_dir))

[('C:\\Users\\User\\Женя\\GitHub\\Программирование\\infosearch\\seminars',
  ['.ipynb_checkpoints'],
  ['sem1_Index.ipynb']),
 ('C:\\Users\\User\\Женя\\GitHub\\Программирование\\infosearch\\seminars\\.ipynb_checkpoints',
  [],
  ['sem1_Index-checkpoint.ipynb'])]

### чтение файла 

In [6]:
filepath = 'test.txt'


# одним массивом  
with open(fpath, 'r') as f:  
    text = f.read() 

    
#по строкам, в конце каждой строки \n  
with open(fpath, 'r') as f:   
    text = f.readlines() 

    
#по строкам, без \n   
with open(fpath, 'r') as f:   
    text = f.read().splitlines() 

NameError: name 'fpath' is not defined

Напоминание про enumerate:    
> При итерации по списку вы можете помимо самого элемента получить его порядковый номер    
``` for i, element in enumerate(your_list): ...  ```    
Иногда для получения элемента делают так -  ``` your_list[i] ```, не надо так

### Пример реализации обратного индекса через CountVectorizer. Пользуйтесь.

In [170]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
 
# инициализируем
vectorizer = CountVectorizer(analyzer='word')

# составляем корпус документов
corpus = [
  'слово1 слово2 слово3',
  'слово2 слово3',
  'слово1 слово2 слово1',
  'слово4'
]

# считаем
X = vectorizer.fit_transform(corpus)
 
# получится следующая структура:
#        | слово1 | слово2 | слово3 | слово4
# текст1 |   1    |    1   |   1    |   0
# текст2 |   0    |    1   |   1    |   0
# текст3 |   2    |    1   |   0    |   0
# текст4 |   0    |    0   |   0    |   1

# показать матрицу
print('X:\n', X.toarray(), '\n')

 
# чтобы получить сгенерированный словарь, из приведенной структуры CountVectorizer
# порядок совпадает с матрицей
print('get_feature_names:', vectorizer.get_feature_names(), '\n')  # ['слово1', 'слово2', 'слово3', 'слово4']
 
    
# чтобы узнать индекс токена в словаре
print('vocabulary_.get:', vectorizer.vocabulary_.get('слово1')) # вернет 0
print('vocabulary_.get:', vectorizer.vocabulary_.get('слово4'), '\n') # вернет 3

 
# теперь можно быстро подсчитать вектор для нового документа
print('transform:', vectorizer.transform(['слово1 слово4 слово4']).toarray())  # результат [[1 0 0 2]]
print('transform:', vectorizer.transform(['слово5']).toarray(), '\n')

 
# чтобы узнать количественное вхождение каждого слова:
matrix_freq = np.asarray(X.sum(axis=0)).ravel()
print('matrix_freq:', matrix_freq, '\n')  # результат [3 3 2 1] 

final_matrix = np.array([np.array(vectorizer.get_feature_names()), matrix_freq])
print('final_matrix:', final_matrix, '\n')  # результат [['слово1' 'слово2' 'слово3' 'слово4'], ['3' '3' '2' '1']] 

X:
 [[1 1 1 0]
 [0 1 1 0]
 [2 1 0 0]
 [0 0 0 1]] 

get_feature_names: ['слово1', 'слово2', 'слово3', 'слово4'] 

vocabulary_.get: 0
vocabulary_.get: 3 

transform: [[1 0 0 2]]
transform: [[0 0 0 0]] 

matrix_freq: [3 3 2 1] 

final_matrix: [['слово1' 'слово2' 'слово3' 'слово4']
 ['3' '3' '2' '1']] 



In [18]:
vectorizer.transform(['слово1 слово4 слово4']).toarray()

array([[1, 0, 0, 2]])

#  Индекс 

Сам по себе индекс - это просто формат хранения данных, он не может осуществлять поиск. Для этого необходимо добавить к нему определенную метрику. Это может быть что-то простое типа булева поиска, а может быть что-то более специфическое или кастомное под задачу.

Давайте посмотрим, что полезного можно вытащить из самого индекса.    
Например, индекс - это информация о частоте встречаемости слова в каждом документе.   
Из этого можно понять, например:
1. какое слово является самым часто употребимым / редким
2. какие слова встречаются всегда вместе - так можно парсить твиттер, fb, форумы и отлавливать новые устойчивые выражения в речи
3. как эти документы кластеризуются по N тематикам согласно словам, которые в них упоминаются 

## __Задача__: 

**Data:** Коллекция субтитров сезонов Друзей. Одна серия - один документ.

**To do:** 

**1 Создайте обратный индекс этой базы, используя CountVectorizer. 
То, что вы получите, называется матрица Term-Document.**

Компоненты вашей реализации:
    - Функция препроцессинга данных. Включите туда лемматизацию, приведение к одному регистру, удаление пунктуации и стоп-слов.
    - Функция индексирования данных. На выходе создает обратный индекс, он же матрица Term-Document.

**2 С помощью обратного индекса посчитайте:** 


a) какое слово является самым частотным

b) какое самым редким

c) какой набор слов есть во всех документах коллекции

d) кто из главных героев статистически самый популярный (упонимается чаще всего)? Имена героев:
- Моника
- Рэйчел 
- Чендлер
- Фиби
- Росс
- Джоуи, Джои

**На что направлены эти задачи:** 
1. Навык построения обратного индекса
2. Навык работы с этим индексом, а именно как с помощью numpy или pandas достать нужную информацию из матрицы данных

[download_friends_corpus](https://yadi.sk/d/4wmU7R8JL-k_RA?w=1)

In [4]:
import os
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

from nltk.corpus import stopwords
STOPWORDS = stopwords.words('russian')

import spacy
nlp = spacy.load('ru_core_news_lg', disable=['ner', 'parser'])

In [5]:
### _check : в коллекции должно быть 165 файлов

In [35]:
corpus = []
for root, dirs, files in os.walk('friends-data'):
    if '.ipynb_checkpoints' not in root:
        for name in files:
            filepath = os.path.join(root, name)
            with open(filepath, encoding='utf-8') as f:
                text = f.read()
                corpus.append(text)
print(len(corpus))

165


Check passed!

In [255]:
def preprocess_text(text):
    doc = nlp(text)
    lemmata = [token.lemma_ for token in doc if token.is_alpha if token.text not in STOPWORDS if token.pos_ != 'PRON']
    lemmata = [lemma for lemma in lemmata if lemma not in STOPWORDS]
    
    return ' '.join(lemmata)

In [37]:
%%time

corpus = [preprocess_text(text) for text in corpus]

Wall time: 1min 22s


In [39]:
vectorizer = CountVectorizer()
index = vectorizer.fit_transform(corpus)

In [51]:
'этот' in STOPWORDS

True

In [49]:
vectorizer.get_feature_names()[index.sum(axis=0).argmax()]

'это'

In [120]:
index.sum(axis=0)[index.sum(axis=0) == index.sum(axis=0).min()]

matrix([[1, 1, 1, ..., 1, 1, 1]], dtype=int64)

In [174]:
a = np.asarray(index.sum(axis=0)).squeeze()

In [209]:
a = np.array([[1, 2, 0], [0, 0, 0], [1, 1, 1]])
a

array([[1, 2, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [210]:
np.all(a, axis=0)

array([False, False, False])

In [235]:
a[:, [0, 1]]

array([[1, 2],
       [0, 0],
       [1, 1]])

In [237]:
c = {}